# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1288/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1288/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fabian/programming/projekt-neutralteam

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fabian/programming/projekt-neutralteam

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/1288/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1288/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fabian/programming/projekt-neutralteam/CMakeFiles /home/fabian/programming/projekt-neutralteam//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fabian/programming/projekt-neutralteam/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PROGRAMM

# Build rule for target.
PROGRAMM: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PROGRAMM
.PHONY : PROGRAMM

# fast build rule for target.
PROGRAMM/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/build
.PHONY : PROGRAMM/fast

#=============================================================================
# Target rules for targets named TEST

# Build rule for target.
TEST: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TEST
.PHONY : TEST

# fast build rule for target.
TEST/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/build
.PHONY : TEST/fast

directNeighbors.o: directNeighbors.cpp.o
.PHONY : directNeighbors.o

# target to build an object file
directNeighbors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/directNeighbors.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/directNeighbors.cpp.o
.PHONY : directNeighbors.cpp.o

directNeighbors.i: directNeighbors.cpp.i
.PHONY : directNeighbors.i

# target to preprocess a source file
directNeighbors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/directNeighbors.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/directNeighbors.cpp.i
.PHONY : directNeighbors.cpp.i

directNeighbors.s: directNeighbors.cpp.s
.PHONY : directNeighbors.s

# target to generate assembly for a file
directNeighbors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/directNeighbors.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/directNeighbors.cpp.s
.PHONY : directNeighbors.cpp.s

enterStudents.o: enterStudents.cpp.o
.PHONY : enterStudents.o

# target to build an object file
enterStudents.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/enterStudents.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/enterStudents.cpp.o
.PHONY : enterStudents.cpp.o

enterStudents.i: enterStudents.cpp.i
.PHONY : enterStudents.i

# target to preprocess a source file
enterStudents.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/enterStudents.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/enterStudents.cpp.i
.PHONY : enterStudents.cpp.i

enterStudents.s: enterStudents.cpp.s
.PHONY : enterStudents.s

# target to generate assembly for a file
enterStudents.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/enterStudents.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/enterStudents.cpp.s
.PHONY : enterStudents.cpp.s

indirectNeighbors.o: indirectNeighbors.cpp.o
.PHONY : indirectNeighbors.o

# target to build an object file
indirectNeighbors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/indirectNeighbors.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/indirectNeighbors.cpp.o
.PHONY : indirectNeighbors.cpp.o

indirectNeighbors.i: indirectNeighbors.cpp.i
.PHONY : indirectNeighbors.i

# target to preprocess a source file
indirectNeighbors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/indirectNeighbors.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/indirectNeighbors.cpp.i
.PHONY : indirectNeighbors.cpp.i

indirectNeighbors.s: indirectNeighbors.cpp.s
.PHONY : indirectNeighbors.s

# target to generate assembly for a file
indirectNeighbors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/indirectNeighbors.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/indirectNeighbors.cpp.s
.PHONY : indirectNeighbors.cpp.s

loadRoom.o: loadRoom.cpp.o
.PHONY : loadRoom.o

# target to build an object file
loadRoom.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/loadRoom.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/loadRoom.cpp.o
.PHONY : loadRoom.cpp.o

loadRoom.i: loadRoom.cpp.i
.PHONY : loadRoom.i

# target to preprocess a source file
loadRoom.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/loadRoom.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/loadRoom.cpp.i
.PHONY : loadRoom.cpp.i

loadRoom.s: loadRoom.cpp.s
.PHONY : loadRoom.s

# target to generate assembly for a file
loadRoom.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/loadRoom.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/loadRoom.cpp.s
.PHONY : loadRoom.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/main.cpp.s
.PHONY : main.cpp.s

menu.o: menu.cpp.o
.PHONY : menu.o

# target to build an object file
menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/menu.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/menu.cpp.o
.PHONY : menu.cpp.o

menu.i: menu.cpp.i
.PHONY : menu.i

# target to preprocess a source file
menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/menu.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/menu.cpp.i
.PHONY : menu.cpp.i

menu.s: menu.cpp.s
.PHONY : menu.s

# target to generate assembly for a file
menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/menu.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/menu.cpp.s
.PHONY : menu.cpp.s

newRoom.o: newRoom.cpp.o
.PHONY : newRoom.o

# target to build an object file
newRoom.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/newRoom.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/newRoom.cpp.o
.PHONY : newRoom.cpp.o

newRoom.i: newRoom.cpp.i
.PHONY : newRoom.i

# target to preprocess a source file
newRoom.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/newRoom.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/newRoom.cpp.i
.PHONY : newRoom.cpp.i

newRoom.s: newRoom.cpp.s
.PHONY : newRoom.s

# target to generate assembly for a file
newRoom.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/newRoom.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/newRoom.cpp.s
.PHONY : newRoom.cpp.s

queryStudents.o: queryStudents.cpp.o
.PHONY : queryStudents.o

# target to build an object file
queryStudents.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/queryStudents.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/queryStudents.cpp.o
.PHONY : queryStudents.cpp.o

queryStudents.i: queryStudents.cpp.i
.PHONY : queryStudents.i

# target to preprocess a source file
queryStudents.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/queryStudents.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/queryStudents.cpp.i
.PHONY : queryStudents.cpp.i

queryStudents.s: queryStudents.cpp.s
.PHONY : queryStudents.s

# target to generate assembly for a file
queryStudents.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/queryStudents.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/queryStudents.cpp.s
.PHONY : queryStudents.cpp.s

room.o: room.cpp.o
.PHONY : room.o

# target to build an object file
room.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/room.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/room.cpp.o
.PHONY : room.cpp.o

room.i: room.cpp.i
.PHONY : room.i

# target to preprocess a source file
room.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/room.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/room.cpp.i
.PHONY : room.cpp.i

room.s: room.cpp.s
.PHONY : room.s

# target to generate assembly for a file
room.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PROGRAMM.dir/build.make CMakeFiles/PROGRAMM.dir/room.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/room.cpp.s
.PHONY : room.cpp.s

tests.o: tests.cpp.o
.PHONY : tests.o

# target to build an object file
tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/tests.cpp.o
.PHONY : tests.cpp.o

tests.i: tests.cpp.i
.PHONY : tests.i

# target to preprocess a source file
tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/tests.cpp.i
.PHONY : tests.cpp.i

tests.s: tests.cpp.s
.PHONY : tests.s

# target to generate assembly for a file
tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TEST.dir/build.make CMakeFiles/TEST.dir/tests.cpp.s
.PHONY : tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PROGRAMM"
	@echo "... TEST"
	@echo "... directNeighbors.o"
	@echo "... directNeighbors.i"
	@echo "... directNeighbors.s"
	@echo "... enterStudents.o"
	@echo "... enterStudents.i"
	@echo "... enterStudents.s"
	@echo "... indirectNeighbors.o"
	@echo "... indirectNeighbors.i"
	@echo "... indirectNeighbors.s"
	@echo "... loadRoom.o"
	@echo "... loadRoom.i"
	@echo "... loadRoom.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... menu.o"
	@echo "... menu.i"
	@echo "... menu.s"
	@echo "... newRoom.o"
	@echo "... newRoom.i"
	@echo "... newRoom.s"
	@echo "... queryStudents.o"
	@echo "... queryStudents.i"
	@echo "... queryStudents.s"
	@echo "... room.o"
	@echo "... room.i"
	@echo "... room.s"
	@echo "... tests.o"
	@echo "... tests.i"
	@echo "... tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

